import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import { Header } from './components/layouts/Header/Header';
import { Footer } from './components/layouts/Footer/Footer';

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'E-Book dealer',
  description: 'Generated by E-Book dealer',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansJP.className}>
        <div className="">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
